USE olist_ecommerce;


-- Q1
-- Calculation: Total Number of Sellers
SELECT 
    COUNT(*) AS total_sellers
FROM sellers;


-- Q2
-- Calculation: Sellers with Orders
SELECT 
    COUNT(DISTINCT seller_id) AS sellers_with_orders
FROM order_items;


-- Q3
-- Calculation: Sellers Without Orders
SELECT 
    COUNT(*) AS sellers_without_orders
FROM sellers s
LEFT JOIN order_items oi
    ON s.seller_id = oi.seller_id
WHERE oi.seller_id IS NULL;


-- Q4
-- Calculation: Total Items Sold by Sellers
SELECT 
    COUNT(*) AS total_items_sold
FROM order_items;


-- Q5
-- Calculation: Total Revenue Generated by Sellers
SELECT 
    ROUND(SUM(price), 2) AS total_seller_revenue
FROM order_items;


-- Q6
-- Calculation: Average Revenue per Seller
SELECT 
    ROUND(AVG(seller_revenue), 2) AS average_revenue_per_seller
FROM (
    SELECT 
        seller_id,
        SUM(price) AS seller_revenue
    FROM order_items
    GROUP BY seller_id
) AS seller_sales;


-- Q7
-- Calculation: Average Items Sold per Seller
SELECT 
    ROUND(AVG(items_sold), 2) AS average_items_per_seller
FROM (
    SELECT 
        seller_id,
        COUNT(*) AS items_sold
    FROM order_items
    GROUP BY seller_id
) AS seller_items;


-- Q8
-- Calculation: Top 10 Sellers by Revenue
SELECT 
    seller_id,
    ROUND(SUM(price), 2) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC
LIMIT 10;


-- Q9
-- Calculation: Top 10 Sellers by Number of Items Sold
SELECT 
    seller_id,
    COUNT(*) AS items_sold
FROM order_items
GROUP BY seller_id
ORDER BY items_sold DESC
LIMIT 10;

-- Calculation: Top 10 Sellers by Average Item Price
SELECT 
    seller_id,
    ROUND(AVG(price), 2) AS average_item_price
FROM order_items
GROUP BY seller_id
ORDER BY average_item_price DESC
LIMIT 10;

-- Calculation: Minimum and Maximum Seller Revenue
SELECT 
    ROUND(MIN(seller_revenue), 2) AS minimum_seller_revenue,
    ROUND(MAX(seller_revenue), 2) AS maximum_seller_revenue
FROM (
    SELECT 
        seller_id,
        SUM(price) AS seller_revenue
    FROM order_items
    GROUP BY seller_id
) AS seller_sales;

-- Calculation: Seller Revenue Distribution
SELECT 
    CASE
        WHEN seller_revenue < 1000 THEN 'Below R$1,000'
        WHEN seller_revenue < 5000 THEN 'R$1,000 - R$4,999'
        WHEN seller_revenue < 10000 THEN 'R$5,000 - R$9,999'
        WHEN seller_revenue < 50000 THEN 'R$10,000 - R$49,999'
        ELSE 'R$50,000+'
    END AS revenue_range,
    COUNT(*) AS seller_count
FROM (
    SELECT 
        seller_id,
        SUM(price) AS seller_revenue
    FROM order_items
    GROUP BY seller_id
) AS seller_sales
GROUP BY revenue_range
ORDER BY MIN(seller_revenue);

-- Calculation: Top 10 Sellers by Freight Revenue
SELECT 
    seller_id,
    ROUND(SUM(freight_value), 2) AS total_freight
FROM order_items
GROUP BY seller_id
ORDER BY total_freight DESC
LIMIT 10;

-- Calculation: Average Freight per Seller
SELECT 
    ROUND(AVG(total_freight), 2) AS average_freight_per_seller
FROM (
    SELECT 
        seller_id,
        SUM(freight_value) AS total_freight
    FROM order_items
    GROUP BY seller_id
) AS seller_freight;

-- Calculation: Top 10 Sellers by Total Order Value Including Freight
SELECT 
    seller_id,
    ROUND(SUM(price + freight_value), 2) AS total_order_value
FROM order_items
GROUP BY seller_id
ORDER BY total_order_value DESC
LIMIT 10;

-- Calculation: Seller Revenue Contribution Percentage
SELECT 
    seller_id,
    ROUND(
        SUM(price) * 100.0 /
        (SELECT SUM(price) FROM order_items),
        2
    ) AS revenue_percentage
FROM order_items
GROUP BY seller_id
ORDER BY revenue_percentage DESC
LIMIT 10;

-- Calculation: Number of Orders Handled by Each Seller
SELECT 
    seller_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM order_items
GROUP BY seller_id
ORDER BY total_orders DESC
LIMIT 10;

-- Calculation: Average Items per Order by Seller
SELECT 
    seller_id,
    ROUND(
        COUNT(*) * 1.0 / COUNT(DISTINCT order_id),
        2
    ) AS average_items_per_order
FROM order_items
GROUP BY seller_id
ORDER BY average_items_per_order DESC
LIMIT 10;

-- Calculation: Sellers with High Revenue and High Item Sales
SELECT 
    seller_id,
    COUNT(*) AS items_sold,
    ROUND(SUM(price), 2) AS total_revenue
FROM order_items
GROUP BY seller_id
HAVING COUNT(*) >= 100
   AND SUM(price) >= 10000
ORDER BY total_revenue DESC;

-- Calculation: Missing Seller Data
SELECT 
    SUM(CASE WHEN seller_id IS NULL THEN 1 ELSE 0 END) AS missing_seller_id,
    SUM(CASE WHEN seller_zip_code_prefix IS NULL THEN 1 ELSE 0 END) AS missing_zip_code,
    SUM(CASE WHEN seller_city IS NULL THEN 1 ELSE 0 END) AS missing_city,
    SUM(CASE WHEN seller_state IS NULL THEN 1 ELSE 0 END) AS missing_state
FROM sellers;